Improvements for RTKNAVI
swift-nav/RTKLIB pull request #77
Opened 2022-03-17 05:12 UTC by ebethon

Add support for the following functionality to RTKNAVI:
1. Support for Wide Lane Ambiguity Resolution
2. Support for Wide Lane Ambiguity Resolution with hold and fix
3. Resize options window for larger AR mode labels

2022-03-17 10:37 UTC, dgburr approved these changes
LGTM

2022-03-17 10:46 UTC, tao-swift approved these changes
lgtm!

2022-03-17 10:46 UTC, tao-swift commented on app/winapp/rtknavi/naviopt.cpp
> +	prcopt.wlmodear=0;
same here.

2022-03-17 10:46 UTC, tao-swift commented on app/winapp/rtknavi/naviopt.cpp
> +	PrcOpt.wlmodear=0;
nit, this line doesn't seem to be needed. prcopt.wlmodear has been initialised as 0 in https://github.com/swift-nav/RTKLIB/blob/fcb4097b272cc682a71f20e2bb5a31e2e098081d/src/rtkcmn.c#L207

2022-03-18 05:51 UTC, silverjam approved these changes

2022-03-18 05:52 UTC, silverjam requested changes
Can we rebase against master and get a clean set of checks?  Latest master should remove Travis so that failure should go away once this is rebased.

2022-03-18 06:10 UTC, silverjam approved these changes

2022-03-18 06:11 UTC, merged